version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  initial:
    executor:
      name: node/default
      tag: "16.17"
    steps:
      - checkout
      - node/install-packages
  test:
    executor:
      name: node/default
      tag: "16.17"
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Test << pipeline.git.branch >>
          command: yarn run test
  deploy:
    executor:
      name: node/default
      tag: "16.17"
    environment:
      REPOURL: << pipeline.project.git_url >>
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Setup evironment variables
          command: |
            echo "export REPOPATH=${REPOURL#https://github.com}" >> "$BASH_ENV"
      - run:
          name: Setup git user
          command: |
            git config --global user.email "githubpkaddress@gmail.com"
            git config --global user.name "Peerawit Khernpratiyut"
      - run:
          name: Setup Github token
          command: |
            echo ${CIRCLE_PROJECT_REPONAME}
            echo ${CIRCLE_REPOSITORY_URL}
            echo ${REPOURL}
            echo ${REPOPATH}
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com${REPOPATH}.git
      - run:
          name: Build << pipeline.git.branch >>
          command: PUBLIC_URL=/${CIRCLE_PROJECT_REPONAME} npm run build
      - run:
          name: Deploy to gh-pages
          command: npm run deploy

workflows:
  test_and_deploy_my_app:
    jobs:
      - initial
      - test:
          requires:
            - initial
      - deploy:
          requires:
            - test
          context:
            - github-context
